### ISSUE TITLE
 "new_empty()"function. Is it a python function or pytorch function?

### ISSUE THREAD

**Issue by wangshanshanAHU** [jxgu1016/MNIST_center_loss.pytorch#14]
Sorry,I can't run the codes because the erro of "new_empty()"function. Is it a python function or pytorch function? I run it below pytorch 0.4 version.

**Comment by jxgu1016** [comment]
```new_empty```is a new method to initialize Tensor since PyTorch 0.4.1. Updating your PyTorch version will fix it.
