### ISSUE TITLE
question about center loss item

### ISSUE THREAD

**Issue by FOURIERWANG** [jxgu1016/MNIST_center_loss.pytorch#15]
Excuse me, the formula says that Xi is a feature dimension that changes with depth. How does the code reflect it? I can't see that. Is feat_dim set as the input dimension, and can it ensure that the optimized output dimension is the final one?  Please answer my question, thank you.

**Comment by jxgu1016** [comment]
Sorry, cannot understand your questions.

**Comment by FOURIERWANG** [comment]
不好意思，我表达的不清楚，我用中文说一下问题。center loss公式里的Xi是随深度变化的特征，代码中的feat_dim和feat指的是输入时的特征维度吗？怎么保证随深度变化我没在代码中看出来，也可能是我理解的不对。而且loss优化的不应该是输出的特征吗？我的问题和自己的理解不到位有所相关，请指教一下。

**Comment by jxgu1016** [comment]
论文里面只在fc上加了center loss，维度需要手工设置。
