### ISSUE TITLE
About the equation(4)

### ISSUE THREAD

**Issue by ghost** [jxgu1016/MNIST_center_loss.pytorch#16]
Excuse me, I note that the gradients of Lc with respect to Ci computed by equation(2) is nearly the same as equation(4). So, could we update Ci  by  automatic differential system as follows: 

Class centerloss(): 
   return Lc/batch_size    %equation(2)

L=L1+Lc
L.backward()

**Comment by jxgu1016** [comment]
The grads of centers don't follow the chain rules, so automatic differential system would not be correct.
