### ISSUE TITLE
a tiny cleanup for `scatter_add_()`

### ISSUE THREAD

**Issue by amirhfarzaneh** [jxgu1016/MNIST_center_loss.pytorch#20]
Since you're doing in-place operation at [line 42](https://github.com/jxgu1016/MNIST_center_loss_pytorch/blob/4e94cc77fe94056a7f1f081fcaf0325781ba0224/CenterLoss.py#L42) of [Centerloss.py](https://github.com/jxgu1016/MNIST_center_loss_pytorch/blob/master/CenterLoss.py). You don't need to re-assign it. So just:

`counts.scatter_add_(0, label.long(), ones)`

**Comment by jxgu1016** [comment]
That's right that ```scatter_add_``` is a in-place op but it also returns the tensor. At line 42 & 43, I use the two styles to show the difference. Anyway, thanks for pointing this out.
