### ISSUE TITLE
about optimizer4nn & optimzer4center

### ISSUE THREAD

**Issue by jiangyanjavawin** [jxgu1016/MNIST_center_loss.pytorch#21]
hello,thanks for your code,it's very import for me to learn center loss,but i don't know the means of  optimzer4center & optimizer4nn,thanks for your reply.

**Comment by jxgu1016** [comment]
**optimzer4center** is to update **centers** (see Alg. 1 step 6 in the paper). **optimizer4nn** is the conventional optimizer for other params except **centers**.
