### ISSUE TITLE
how to update center？

### ISSUE THREAD

**Issue by vincezengqiang** [jxgu1016/MNIST_center_loss.pytorch#23]
hihi,thx for u to provide such a excellent work, and i want to know how to update class center?

**Comment by vincezengqiang** [comment]
backward（）中的grad_centers是不是就是对应论文中公式4的Δcj，是不是可以用center减去grad_centers来更新center？
期待您的解答，感谢！

**Comment by vincezengqiang** [comment]
研究了下backward的原理，会计算grad_centers的梯度，在反传、优化器优化过程中center会自动更新，是吗？不需要显示的进行center更新操作，对吗？  对自定义loss接触的比较少，还请不吝赐教！感谢

**Comment by ReverseSystem001** [comment]
> 研究了下backward的原理，会计算grad_centers的梯度，在反传、优化器优化过程中center会自动更新，是吗？不需要显示的进行center更新操作，对吗？ 对自定义loss接触的比较少，还请不吝赐教！感谢

so, what is the answer?
